### ISSUE TITLE
can not get to show page

### ISSUE THREAD

**Issue by stevengcooper** [TIYTheScenery/TheSceneryAngular#40]
According to console it is looking for the user id in local storage and blowing up angular when it can't find it

**Comment by stevengcooper** [comment]
Performance goes to half of a show page with no info displayed. 
Company goes to an edit page.

**Comment by stevengcooper** [comment]
Can only get to show page if logged in as a professional. 
Logged in as a non professional user or not logged in at all is where the issue lies.

**Comment by byarsawich** [comment]
fixed

**Comment by stevengcooper** [comment]
confirmed
