### ISSUE TITLE
clicking create company button causes a 500 error on the server

### ISSUE THREAD

**Issue by BestMattEver** [TIYTheScenery/TheSceneryAngular#62]

**Comment by BestMattEver** [comment]
possibly related to having a company id in local storage previously? possibly an id for a company that doesn't exist?

**Comment by BestMattEver** [comment]
possibly an error with the create and show and edit variables?

**Comment by BestMattEver** [comment]
MAKE SURE THE WHAT VARIABLE IN TOCOMPANY() IS FILLED IN IN THE HTML

**Comment by byarsawich** [comment]
this was fixed in last bug sprint
